<a href="https://colab.research.google.com/github/kaustavr19/Data-Science_ML----Projects-Resources/blob/main/Data-Science_ML----Projects-Resources/Study%20%26%20Resource/ML%20Revise/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


## The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#get dimension
a.ndim

1

In [6]:
b.shape #shape

(2, 3)

In [7]:
#get datatype
a.dtype

dtype('int32')

In [8]:
#get size
a.itemsize

4

In [9]:
#get total size
a.nbytes

12

In [10]:
#get number of elements
a.size

3

##Accessing/Changing elements, rows, columns

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
#get specific element
a[1,5]

13

In [13]:
#get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#get specific column
a[:, 2]

array([ 3, 10])

In [15]:
#get in a range
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20

a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


###3d example

In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
b[0,1,1]

4

In [19]:
#replace
#b[:,1,:] = [[9,9,9],[8,8]]
b[:,1,:] = [[9,9],[8,8]]

In [20]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

##Initialize diff. types of arrays

In [21]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [23]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
#any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
#random decimal numbers
np.random.rand(4,2)

array([[0.31221654, 0.35111109],
       [0.67777265, 0.50537454],
       [0.17329516, 0.03808106],
       [0.16279301, 0.80789615]])

In [26]:
#random integer value
np.random.randint(-4,8, size=(3,3))

array([[-2, -2, -3],
       [ 0, -1,  4],
       [ 1,  1,  2]])

In [27]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##Mathematics

In [30]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a+2

array([3, 4, 5, 6])

In [32]:
a-2

array([-1,  0,  1,  2])

In [33]:
a*2

array([2, 4, 6, 8])

In [34]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [35]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [36]:
a**2

array([ 1,  4,  9, 16])

In [37]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

###Linear Algebra

In [38]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [39]:
#find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)


###Stats

In [40]:
stats = np.array([[1,2,3,],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats)

1

In [44]:
np.max(stats, axis=1)

array([3, 6])

In [45]:
np.sum(stats, axis=0)

array([5, 7, 9])

##Reorganize Arrays

In [50]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [51]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##Miscellaneous

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

##Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))